[minikube]
cpus = 4
memory = 8192

[[container_registry]]
name = "registry-1"
url = "some.registry.url"
username = "${env.HARBOR_USERNAME}"
password = "${env.HARBOR_SECRET}"

[[helm_chart_repo]]
name = "helm-chart-repo-1"
url = "some.registry.url/chartrepo"
username = "${env.HARBOR_USERNAME}"
password = "${env.HARBOR_SECRET}"

[[helmchart]]
name = "helm-chart-1"
container_registry = "registry-1"
helm_chart_repo = "helm-chart-repo-1"
repo = "chart-repo"

[[helmchart]]
name = "helm-chart-2"
container_registry = "registry-1"
helm_chart_repo = "helm-chart-repo-1"
repo = "chart-repo"

[[helmchart]]
name = "helm-chart-3"
container_registry = "registry-1"
helm_chart_repo = "helm-chart-repo-1"
repo = "some-different-chart-repo"
