[minikube]
cpus = 4
memory = 8192

[[registry]]
name = "registry-1"
url = "some.registry.url"
helm_repo_url = "some.registry.url/chartrepo"
username = "${env.HARBOR_USERNAME}"
password = "${env.HARBOR_SECRET}"

[[helmchart]]
name = "helm-chart-1"
registry = "registry-1"
repo = "chart-repo"

[[helmchart]]
name = "helm-chart-2"
registry = "registry-1"
repo = "chart-repo"

[[helmchart]]
name = "helm-chart-3"
registry = "registry-1"
repo = "some-different-chart-repo"
