on:
  push:
    tags:
      - "v*"
name: Release
jobs:
  build:
    name: Release (crates.io & github.com)
    runs-on: ubuntu-latest
    env:
      BINARY_NAME: kleinwuerfel
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v2
      - run: cargo login ${CARGO_RELEASE_TOKEN}
        env:
          CARGO_RELEASE_TOKEN: ${{ secrets.CARGO_RELEASE_TOKEN }}
      - run: cargo publish
      - uses: docker://messense/rust-musl-cross:x86_64-musl
        with:
          args: cargo build --release
      - uses: docker://messense/rust-musl-cross:x86_64-musl
        with:
          args: musl-strip target/x86_64-unknown-linux-musl/release/kleinwuerfel
      - run: cp ./target/x86_64-unknown-linux-musl/release/kleinwuerfel kleinwuerfel
      - run: sha512sum kleinwuerfel > kleinwuerfel.sha512sum
      - id: github_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release kleinwuerfel ${{ github.ref }}
          body: "No changelog, but [here](https://cataas.com/cat) is a random cat GIF for your amusement!"
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.github_release.outputs.upload_url }}
          asset_path: ./kleinwuerfel
          asset_name: kleinwuerfel
          asset_content_type: application/octet-stream
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.github_release.outputs.upload_url }}
          asset_path: ./kleinwuerfel.sha512sum
          asset_name: kleinwuerfel.sha512sum
          asset_content_type: text/plain
